[general]
live_config_reload = true
import = [
	"~/.config/alacritty/themes/kanagawa_wave.toml"
]

[window]
dynamic_title = true

[font]
normal = { family = "SauceCodePro Nerd Font", style = "SemiBold" }
size = 11


[shell]
program = "/bin/bash"
args = ["-l"]
